# ----------------------------------------------- #
# Note: this file originates in template-template #
# ----------------------------------------------- #

quiet: true
skip-check:
  - CKV_DOCKER_2
  - CKV_DOCKER_8
  - CKV_GHA_3
  - BC_DKR_3
  - CKV_GIT_1
  - CKV_GIT_5
  - CKV_GIT_6
  - CKV_TF_1
